# sudo docker run -dit --name basic -p 8080:80 -v /home/ubuntu/cicd-gaddis12/project6/websites:/usr/local/apache2/htdocs/ httpd:2.4
From httpd:2.4
COPY /home/ubuntu/cicd-gaddis12/project6/websites /usr/local/apache2/htdocs/
EXPOSE 80