name: Publish Docker image

on:
  push:
    branches: [main]
  release:
    types: [published]
env: DOCKER_HUB_REPO: gaddis12/mysite
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: httpd-2.4
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{env.DOCKER_HUB_REPO }}
          tag_with_ref: true
